spring.application.name=banco-api
# Configuracao do Servidor
server.port=8080

# Configuracao da Base de Dados H2
spring.datasource.url=jdbc:h2:mem:bancodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativacao da Consola Web do H2 no Navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracoes do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true